### ISSUE TITLE
좌측 리스트 스크롤 시, 리스트 아이템의 회사 아이콘이 검색창 위로 떠버림

### ISSUE THREAD

**Issue by DAWNCR0W** [SoonGwan/ItEuljido#28]
<img width="188" alt="스크린샷 2021-06-09 오전 11 16 31" src="https://user-images.githubusercontent.com/31297498/121282262-260f5500-c914-11eb-96bd-d686c473d72e.png">

좌측 리스트 스크롤 시, 리스트 아이템의 회사 이미지가 검색창 위로 떠버림.

**Comment by SoonGwan** [comment]
InputWrapper에 z-index가 없어 발생한 현상을 수정하였습니다!
감사합니다 :)
