### ISSUE TITLE
key 값은 고유한 값으로 쓰면 좋을거 같습니당

### ISSUE THREAD

**Issue by mango906** [SoonGwan/ItEuljido#43]
구현물보다가 뭔가 key가 인덱스인거같아서 코드 보니 key가 인덱스 값으로 쓰이고 있더라구요
리액트에서 key 값은 고유한 값이어야 하기때문에 index를 사용하기 보단, id 값을 사용하는게 좋을거 같아여

https://github.com/SoonGwan/ItEuljido/blob/4f35d622707beca6eee4ca4ab1ed923a150b95ad/src/container/NavContainer/NavContainer.tsx#L43-L54

왜 key가 고유한 값이어야 하는지는 리액트 재조정 단계를 읽어보면 이해할 수 있을겁니당

[리액트 재조정 단계](https://ko.reactjs.org/docs/reconciliation.html#recursing-on-children)

**Comment by SoonGwan** [comment]
감사합니다!
여태까지 해당 부분을 고려하지 못한 제 자신이 부끄러워 지는군요!! ㅠㅠ
도움을 주셔서 감사합니다!

**Comment by mango906** [comment]
아닙니당 잘하고 계셔유 화이팅화이팅
